# Generated by Django 5.2.8 on 2025-12-03 22:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Auditoría')),
                ('nombre_tabla', models.CharField(max_length=100, verbose_name='Nombre Tabla')),
                ('id_registro', models.CharField(max_length=100, verbose_name='ID Registro')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Operación')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('usuario_responsable', models.CharField(max_length=50, verbose_name='Usuario Responsable')),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección IP')),
            ],
            options={
                'db_table': 'AUDITORIA',
            },
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('tipo_inscripcion', models.CharField(max_length=50, verbose_name='Tipo Inscripción')),
                ('tipo_contribuyente', models.CharField(max_length=50, verbose_name='Tipo Contribuyente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'CONTRIBUYENTE',
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('tipo_dato', models.CharField(max_length=50, verbose_name='Tipo de Dato')),
                ('sistema', models.CharField(max_length=50, verbose_name='Sistema')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
            options={
                'db_table': 'PARAMETRO_SISTEMA',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('codigo_permiso', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Permiso')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
                ('nivel_acceso', models.IntegerField(verbose_name='Nivel Acceso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'PERMISO',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID Rol')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('maneja_nivel', models.BooleanField(default=False, verbose_name='Maneja Nivel')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('maneja_area', models.BooleanField(default=False, verbose_name='Maneja Área')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('permiso_especial', models.BooleanField(default=False, verbose_name='Permiso Especial')),
                ('simbolo_rol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Símbolo')),
            ],
            options={
                'db_table': 'ROL_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='TipoCalificacion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Mínimo')),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Máximo')),
                ('requisitos', models.CharField(max_length=100, verbose_name='Requisitos')),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'TIPO_CALIFICACION',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('modulo_validacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Módulo Validación')),
                ('dias_vencimiento', models.IntegerField(default=0, verbose_name='Días Vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('id_calificacion', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Calificación')),
                ('fecha_calificacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Calificación')),
                ('monto_anual', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Anual')),
                ('periodo', models.IntegerField(verbose_name='Periodo')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('rut_contribuyente', models.ForeignKey(db_column='rut_contribuyente', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='taxgrades.contribuyente')),
                ('codigo_tipo_calificacion', models.ForeignKey(db_column='codigo_tipo_calificacion', on_delete=django.db.models.deletion.PROTECT, to='taxgrades.tipocalificacion')),
            ],
            options={
                'db_table': 'CALIFICACION_TRIBUTARIA',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCalificacion',
            fields=[
                ('id_historico', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Histórico')),
                ('rut_contribuyente', models.CharField(max_length=20, verbose_name='RUT Contribuyente')),
                ('codigo_tipo_calificacion', models.CharField(max_length=10, verbose_name='Tipo Calificación')),
                ('fecha_calificacion', models.DateField(verbose_name='Fecha Calificación')),
                ('monto_anual', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Anual')),
                ('periodo', models.IntegerField(verbose_name='Periodo')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('vigente', models.BooleanField(verbose_name='Vigente')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Modificación')),
                ('usuario_modificacion', models.CharField(max_length=50, verbose_name='Usuario Modificación')),
                ('tipo_modificacion', models.CharField(max_length=50, verbose_name='Tipo Modificación')),
                ('id_calificacion', models.ForeignKey(db_column='id_calificacion', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.calificaciontributaria')),
            ],
            options={
                'db_table': 'HISTORICO_CALIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID Notificación')),
                ('tipo_notificacion', models.CharField(max_length=50, verbose_name='Tipo Notificación')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Envío')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lectura')),
                ('rut_contribuyente', models.ForeignKey(db_column='rut_contribuyente', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.contribuyente')),
            ],
            options={
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('id_usuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('contrasena_hash', models.CharField(max_length=255, verbose_name='Hash Contraseña')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('intentos_fallidos', models.IntegerField(default=0, verbose_name='Intentos Fallidos')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Bloqueo')),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, to='taxgrades.rolusuario')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id_sesion', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID Sesión')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('ip_origen', models.CharField(max_length=45, verbose_name='IP Origen')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('token_acceso', models.TextField(verbose_name='Token Acceso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.usuario')),
            ],
            options={
                'db_table': 'SESION_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id_documento', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Documento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('folio', models.CharField(max_length=50, verbose_name='Folio')),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Neto')),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Impuesto')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Total')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('url_archivo', models.TextField(verbose_name='URL Archivo')),
                ('hash_archivo', models.CharField(max_length=255, verbose_name='Hash Archivo')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación')),
                ('rut_contribuyente', models.ForeignKey(db_column='rut_contribuyente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='taxgrades.contribuyente')),
                ('codigo_tipo_documento', models.ForeignKey(db_column='codigo_tipo_documento', on_delete=django.db.models.deletion.PROTECT, to='taxgrades.tipodocumento')),
                ('usuario_validacion', models.ForeignKey(db_column='usuario_validacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxgrades.usuario')),
            ],
            options={
                'db_table': 'DOCUMENTO_TRIBUTARIO',
            },
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='usuario_actualizacion',
            field=models.ForeignKey(db_column='usuario_actualizacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuyentes_actualizados', to='taxgrades.usuario'),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='usuario_creacion',
            field=models.ForeignKey(db_column='usuario_creacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuyentes_creados', to='taxgrades.usuario'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario_actualizacion',
            field=models.ForeignKey(db_column='usuario_actualizacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_actualizadas', to='taxgrades.usuario'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario_creacion',
            field=models.ForeignKey(db_column='usuario_creacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to='taxgrades.usuario'),
        ),
        migrations.CreateModel(
            name='ValidacionTributaria',
            fields=[
                ('id_validacion', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Validación')),
                ('rut_contribuyente', models.CharField(max_length=20, verbose_name='RUT Contribuyente')),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Validación')),
                ('resultado', models.CharField(max_length=50, verbose_name='Resultado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('reglas_validacion', models.JSONField(blank=True, null=True, verbose_name='Reglas Aplicadas')),
                ('usuario_validador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario Validador')),
                ('id_documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.documentotributario')),
            ],
            options={
                'db_table': 'VALIDACION_TRIBUTARIA',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedido', models.BooleanField(default=True, verbose_name='Concedido')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Asignación')),
                ('codigo_permiso', models.ForeignKey(db_column='codigo_permiso', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.permiso')),
                ('codigo_rol', models.ForeignKey(db_column='codigo_rol', on_delete=django.db.models.deletion.CASCADE, to='taxgrades.rolusuario')),
            ],
            options={
                'db_table': 'ROL_PERMISO',
                'unique_together': {('codigo_rol', 'codigo_permiso')},
            },
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['rut_contribuyente', 'periodo'], name='CALIFICACIO_rut_con_0b7a55_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['estado'], name='CALIFICACIO_estado_58bbf1_idx'),
        ),
    ]
